/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { AccountsService } from "../accounts.service";
import { AccountsCreateInput } from "./AccountsCreateInput";
import { Accounts } from "./Accounts";
import { AccountsFindManyArgs } from "./AccountsFindManyArgs";
import { AccountsWhereUniqueInput } from "./AccountsWhereUniqueInput";
import { AccountsUpdateInput } from "./AccountsUpdateInput";

export class AccountsControllerBase {
  constructor(protected readonly service: AccountsService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Accounts })
  async createAccounts(
    @common.Body() data: AccountsCreateInput
  ): Promise<Accounts> {
    return await this.service.createAccounts({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Accounts] })
  @ApiNestedQuery(AccountsFindManyArgs)
  async accountsItems(@common.Req() request: Request): Promise<Accounts[]> {
    const args = plainToClass(AccountsFindManyArgs, request.query);
    return this.service.accountsItems({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Accounts })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async accounts(
    @common.Param() params: AccountsWhereUniqueInput
  ): Promise<Accounts | null> {
    const result = await this.service.accounts({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Accounts })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateAccounts(
    @common.Param() params: AccountsWhereUniqueInput,
    @common.Body() data: AccountsUpdateInput
  ): Promise<Accounts | null> {
    try {
      return await this.service.updateAccounts({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Accounts })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteAccounts(
    @common.Param() params: AccountsWhereUniqueInput
  ): Promise<Accounts | null> {
    try {
      return await this.service.deleteAccounts({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
