/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { DunningNotifications } from "./DunningNotifications";
import { DunningNotificationsCountArgs } from "./DunningNotificationsCountArgs";
import { DunningNotificationsFindManyArgs } from "./DunningNotificationsFindManyArgs";
import { DunningNotificationsFindUniqueArgs } from "./DunningNotificationsFindUniqueArgs";
import { DeleteDunningNotificationsArgs } from "./DeleteDunningNotificationsArgs";
import { DunningNotificationsService } from "../dunningNotifications.service";
@graphql.Resolver(() => DunningNotifications)
export class DunningNotificationsResolverBase {
  constructor(protected readonly service: DunningNotificationsService) {}

  async _dunningNotificationsItemsMeta(
    @graphql.Args() args: DunningNotificationsCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [DunningNotifications])
  async dunningNotificationsItems(
    @graphql.Args() args: DunningNotificationsFindManyArgs
  ): Promise<DunningNotifications[]> {
    return this.service.dunningNotificationsItems(args);
  }

  @graphql.Query(() => DunningNotifications, { nullable: true })
  async dunningNotifications(
    @graphql.Args() args: DunningNotificationsFindUniqueArgs
  ): Promise<DunningNotifications | null> {
    const result = await this.service.dunningNotifications(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => DunningNotifications)
  async deleteDunningNotifications(
    @graphql.Args() args: DeleteDunningNotificationsArgs
  ): Promise<DunningNotifications | null> {
    try {
      return await this.service.deleteDunningNotifications(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
